### ISSUE TITLE
[HOMEWORK] DAO_ANH_TUAN KIND_RUNNING_EVIDENCE

### ISSUE THREAD

**Issue by anhtuanpc** [nebula-labs/training#5]
## Homework request
Yêu cầu:

1. Cài đặt và chạy thành công Docker không cần quyền root

2. Cài đặt thành công Kubernetes

3. Chạy thành công KIND (Kubernetes in Docker) trên Kubernetes

4. Cài đặt thành công golang, có ~/go/bịn trong $PATH

## Homework proof
![Uploading rootless_docker.jpg…]()
![intall_kubectl](https://user-images.githubusercontent.com/64728654/229296052-15e2cbdc-5f4e-47b0-af6a-6a28411f9eed.jpg
![golang](https://user-images.githubusercontent.com/64728654/229296066-4e994519-9f53-4a8e-ba92-9c9517a44521.jpg)
)
![Run_kind_successfully](https://user-images.githubusercontent.com/64728654/229296075-7501049b-7981-4994-9034-2e813ccfc80e.jpg)

**Comment by anhtuanpc** [comment]
I think just running kind create cluster successfully can prove all of the requirements above of homework tests as kind prerequisite requires installing rootless docker, k8s, and  install via golang.

**Comment by anhtuanpc** [comment]
Maybe some images were break because the error of uploading files.

**Comment by nghuyenthevinh2000** [comment]
that should be enough to pass
